### ISSUE TITLE
Request - Use scroll wheel to adjust sliders on hover

### ISSUE THREAD

**Issue by ItMeCorban** [GoXLR-on-Linux/goxlr-ui#1]
Adjust the volume of the web ui sliders by using the mouse scroll wheel while the cursor is hovering over them. The same way a brightness slider works in most panels

**Comment by FrostyCoolSlug** [comment]
This likely isn't something I can fix in the immediate future.. One of the problems with how the UI represents those sliders is that they're standard horizontal HTML5 range sliders, but with a CSS modification that simply rotates them 90 degrees to be vertical. 

Currently everyone does 'vertical' sliders differently, with various bugs and issues, and there's no agreed upon method for handling them (in Webkit / Blink as far as I'm aware, you can't style them at all due to conflicting requirements), so this method really doesn't work in the current scope of the code.

With that said, I'm likely going to end up creating a specialized slider component, that can be rendered and behave as someone would expect them to, but it's not going to be on the front line for a little bit.

I'll keep this request open for now, until the problem can be solved, as this is a super useful feature!

**Comment by vodkapmp** [comment]
Could one make the input field underneath the sliders wheelable?
I've seen it quite often that text/number fields on websites are possible to increment with the scroll wheel, so might be easier to solve than the sliders themselves.

It isn't the exactly the requested feature, but might be a good enough solution?

**Comment by ItMeCorban** [comment]
Yeah that could work - I guess you'd just make it such that have the cursor in the box surround the slider counts, that way scrolling anywhere around it changes both the number and slider.
For the numbers I tend to prefer Adobe's method where you can click and drag left and right to increment as if it were a scroll bar.

**Comment by NinjaLabs-Dev** [comment]
@FrostyCoolSlug Can this be closed now with #24 being merged?

**Comment by FrostyCoolSlug** [comment]
Absolutely, thanks!
